/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menuUtama;

import akunSaya.ViewMenuAkunSayaEdit;
import akunSaya.ViewSettings;
import checkout.ViewCheckOut;
import database.koneksiDatabase;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SpinnerNumberModel;
import login.ViewLogin;
import pesananSaya.ViewMenuPesananSaya;
import pesananSaya.ViewMenuPesananSayaEmpty;

public class ViewMenuUtama extends javax.swing.JFrame {

    public static ViewCheckOut checkout = null;
    ImageIcon icon = new ImageIcon("src/img/logo.png");

    public void myInitComponents() {
        spinnerProduk1.setModel(new SpinnerNumberModel(0, 0, 9999, 1));
        spinnerProduk2.setModel(new SpinnerNumberModel(0, 0, 9999, 1));
        spinnerProduk3.setModel(new SpinnerNumberModel(0, 0, 9999, 1));
        spinnerProduk4.setModel(new SpinnerNumberModel(0, 0, 9999, 1));
        spinnerProduk5.setModel(new SpinnerNumberModel(0, 0, 9999, 1));
        spinnerProduk6.setModel(new SpinnerNumberModel(0, 0, 9999, 1));
    }
    public String name, pass;

    private static ViewMenuUtama instance = null;

    private void ViewMenuUtama() {

    }

    public static ViewMenuUtama getViewMenuUtama() throws IOException, FileNotFoundException, SQLException {
        if (instance == null) {
            instance = new ViewMenuUtama();
        }
        return instance;
    }

    ViewLogin login = new ViewLogin();

    public static void setUsernameLB(JLabel usernameLB) {
        ViewMenuUtama.usernameLB = usernameLB;
    }

    public static JLabel getUsernameLB() {
        return usernameLB;
    }

    public void getUsername() throws IOException, FileNotFoundException, SQLException {
        name = ViewLogin.getViewLogin().name;

        Statement stat;

        stat = (Statement) koneksiDatabase.getKoneksi().createStatement();
        String sql = "SELECT * FROM informasi_akun WHERE username = '" + name + "'";
//        String sql = "SELECT * FROM informasi_akun";
        ResultSet res = stat.executeQuery(sql);

        while (res.next()) {
            String username = res.getString("username");

            usernameLB.setText(username);
        }
    }

    private final JPopupMenu popupMenu = new JPopupMenu();
    private JMenuItem menuItem = null;

    public ViewMenuUtama() throws IOException, FileNotFoundException, SQLException {
        initComponents();
        myInitComponents();
        setIconImage(icon.getImage());
        checkout = new ViewCheckOut();
        // Call Our Method
        createPopupMenu(this);

        getUsername();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        akunIcon = new javax.swing.JLabel();
        usernameLB = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        namaProduk1 = new javax.swing.JLabel();
        hargaProduk1 = new javax.swing.JLabel();
        beliBT1 = new javax.swing.JButton();
        namaProduk2 = new javax.swing.JLabel();
        beliBT2 = new javax.swing.JButton();
        namaProduk3 = new javax.swing.JLabel();
        beliBT3 = new javax.swing.JButton();
        namaProduk4 = new javax.swing.JLabel();
        beliBT4 = new javax.swing.JButton();
        namaProduk5 = new javax.swing.JLabel();
        beliBT5 = new javax.swing.JButton();
        namaProduk6 = new javax.swing.JLabel();
        beliBT6 = new javax.swing.JButton();
        spinnerProduk1 = new javax.swing.JSpinner();
        spinnerProduk2 = new javax.swing.JSpinner();
        spinnerProduk3 = new javax.swing.JSpinner();
        spinnerProduk4 = new javax.swing.JSpinner();
        spinnerProduk5 = new javax.swing.JSpinner();
        spinnerProduk6 = new javax.swing.JSpinner();
        gambar2 = new javax.swing.JLabel();
        gambar3 = new javax.swing.JLabel();
        gambar4 = new javax.swing.JLabel();
        gambar5 = new javax.swing.JLabel();
        gambar6 = new javax.swing.JLabel();
        gambar1 = new javax.swing.JLabel();
        hargaProduk3 = new javax.swing.JLabel();
        hargaProduk2 = new javax.swing.JLabel();
        hargaProduk4 = new javax.swing.JLabel();
        hargaProduk5 = new javax.swing.JLabel();
        hargaProduk6 = new javax.swing.JLabel();
        checkoutBT = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jumlahKeranjangBelanjaTF = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        subTotalTF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Get Your Dimsum");
        setMinimumSize(new java.awt.Dimension(524, 268));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(223, 164, 164));
        jPanel1.setPreferredSize(new java.awt.Dimension(356, 839));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Raleway", 3, 14)); // NOI18N
        jLabel2.setText("Made with love to bless your tummy");

        jLabel4.setFont(new java.awt.Font("Raleway", 3, 16)); // NOI18N
        jLabel4.setText("Est. 2019");

        jLabel5.setFont(new java.awt.Font("Raleway", 3, 16)); // NOI18N
        jLabel5.setText("We are present in");

        jLabel6.setFont(new java.awt.Font("Raleway", 3, 16)); // NOI18N
        jLabel6.setText("Jakarta");

        jLabel12.setFont(new java.awt.Font("Raleway", 3, 16)); // NOI18N
        jLabel12.setText("Bogor");

        jLabel13.setFont(new java.awt.Font("Raleway", 3, 16)); // NOI18N
        jLabel13.setText("Depok");

        jLabel14.setFont(new java.awt.Font("Raleway", 3, 16)); // NOI18N
        jLabel14.setText("Tangerang");

        jLabel15.setFont(new java.awt.Font("Raleway", 3, 16)); // NOI18N
        jLabel15.setText("Bekasi");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unsika.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fasilkom.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel13)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel14))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel15)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(jLabel12)
                .addGap(1, 1, 1)
                .addComponent(jLabel13)
                .addGap(0, 0, 0)
                .addComponent(jLabel14)
                .addGap(0, 0, 0)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(112, 112, 112));
        jLabel7.setText("Menu Utama");

        jPanel3.setBackground(new java.awt.Color(187, 151, 151));

        akunIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/account.png"))); // NOI18N
        akunIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        akunIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                akunIconMouseClicked(evt);
            }
        });

        usernameLB.setFont(new java.awt.Font("Raleway", 1, 18)); // NOI18N
        usernameLB.setText("Nama Pengguna");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(akunIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameLB)
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(usernameLB))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(akunIcon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cart.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Raleway", 1, 18)); // NOI18N
        jLabel9.setText("Keranjang Anda");

        jLabel10.setFont(new java.awt.Font("Raleway", 1, 16)); // NOI18N
        jLabel10.setText("Sub-Total : Rp");

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        namaProduk1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaProduk1.setText("Dimsum Ayam");

        hargaProduk1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hargaProduk1.setText("3000");

        beliBT1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        beliBT1.setText("Beli");
        beliBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliBT1ActionPerformed(evt);
            }
        });

        namaProduk2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaProduk2.setText("Dimsum Sapi");

        beliBT2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        beliBT2.setText("Beli");
        beliBT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliBT2ActionPerformed(evt);
            }
        });

        namaProduk3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaProduk3.setText("Dimsum Keju");

        beliBT3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        beliBT3.setText("Beli");
        beliBT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliBT3ActionPerformed(evt);
            }
        });

        namaProduk4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaProduk4.setText("Dimsum Extra Keju");

        beliBT4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        beliBT4.setText("Beli");
        beliBT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliBT4ActionPerformed(evt);
            }
        });

        namaProduk5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaProduk5.setText("Dimsum Penyet");

        beliBT5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        beliBT5.setText("Beli");
        beliBT5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliBT5ActionPerformed(evt);
            }
        });

        namaProduk6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaProduk6.setText("Dimsum Rendang plus");

        beliBT6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        beliBT6.setText("Beli");
        beliBT6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliBT6ActionPerformed(evt);
            }
        });

        spinnerProduk1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerProduk1StateChanged(evt);
            }
        });

        spinnerProduk2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerProduk2StateChanged(evt);
            }
        });

        spinnerProduk3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerProduk3StateChanged(evt);
            }
        });

        spinnerProduk4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerProduk4StateChanged(evt);
            }
        });

        spinnerProduk5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerProduk5StateChanged(evt);
            }
        });

        spinnerProduk6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerProduk6StateChanged(evt);
            }
        });

        gambar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produkImage/02.jpeg"))); // NOI18N
        gambar2.setToolTipText("C:\\\\Users\\\\hp\\\\Documents\\\\NetBeansProjects\\\\Get Your Dimsum\\\\src\\\\produkImage\\\\02.jpeg");

        gambar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produkImage/03.jpeg"))); // NOI18N
        gambar3.setToolTipText("C:\\\\Users\\\\hp\\\\Documents\\\\NetBeansProjects\\\\Get Your Dimsum\\\\src\\\\produkImage\\\\03.jpeg");

        gambar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produkImage/04.jpeg"))); // NOI18N
        gambar4.setToolTipText("C:\\\\Users\\\\hp\\\\Documents\\\\NetBeansProjects\\\\Get Your Dimsum\\\\src\\\\produkImage\\\\04.jpeg");

        gambar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produkImage/05.jpeg"))); // NOI18N
        gambar5.setToolTipText("C:\\\\Users\\\\hp\\\\Documents\\\\NetBeansProjects\\\\Get Your Dimsum\\\\src\\\\produkImage\\\\05.jpeg");

        gambar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produkImage/06.jpeg"))); // NOI18N
        gambar6.setToolTipText("C:\\\\Users\\\\hp\\\\Documents\\\\NetBeansProjects\\\\Get Your Dimsum\\\\src\\\\produkImage\\\\06.jpeg");

        gambar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/produkImage/01.jpeg"))); // NOI18N
        gambar1.setToolTipText("C:\\\\Users\\\\hp\\\\Documents\\\\NetBeansProjects\\\\Get Your Dimsum\\\\src\\\\produkImage\\\\01.jpeg");

        hargaProduk3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hargaProduk3.setText("3500");

        hargaProduk2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hargaProduk2.setText("3000");

        hargaProduk4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hargaProduk4.setText("4000");

        hargaProduk5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hargaProduk5.setText("4500");

        hargaProduk6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hargaProduk6.setText("5000");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaProduk4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(spinnerProduk4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(beliBT4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(hargaProduk1)
                    .addComponent(namaProduk1)
                    .addComponent(gambar4)
                    .addComponent(hargaProduk4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(spinnerProduk1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(beliBT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(spinnerProduk2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(beliBT2))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(hargaProduk5)
                            .addGap(18, 18, 18)
                            .addComponent(spinnerProduk5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(beliBT5)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaProduk2)
                            .addComponent(namaProduk2)
                            .addComponent(gambar5)
                            .addComponent(namaProduk5))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(spinnerProduk6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(beliBT6)
                                .addContainerGap(43, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(spinnerProduk3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(beliBT3)
                                .addGap(20, 20, 20))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaProduk6)
                            .addComponent(gambar6)
                            .addComponent(hargaProduk6)
                            .addComponent(namaProduk3)
                            .addComponent(hargaProduk3))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gambar1)
                .addGap(39, 39, 39)
                .addComponent(gambar2)
                .addGap(39, 39, 39)
                .addComponent(gambar3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gambar2)
                    .addComponent(gambar3)
                    .addComponent(gambar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(namaProduk1)
                        .addGap(2, 2, 2)
                        .addComponent(hargaProduk1)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(beliBT1)
                            .addComponent(spinnerProduk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(beliBT2)
                                    .addComponent(spinnerProduk2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hargaProduk2)
                                    .addComponent(hargaProduk3))))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(namaProduk2)
                                .addComponent(namaProduk3))
                            .addGap(25, 25, 25)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(beliBT3)
                                .addComponent(spinnerProduk3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gambar5)
                    .addComponent(gambar4)
                    .addComponent(gambar6))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(namaProduk4)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(beliBT4)
                            .addComponent(spinnerProduk4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(hargaProduk4)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(beliBT5)
                            .addComponent(spinnerProduk5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaProduk6)
                            .addComponent(namaProduk5))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(beliBT6)
                                    .addComponent(spinnerProduk6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hargaProduk5)
                                .addComponent(hargaProduk6)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        checkoutBT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        checkoutBT.setText("Checkout");
        checkoutBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBTActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));

        jumlahKeranjangBelanjaTF.setFont(new java.awt.Font("Raleway", 1, 18)); // NOI18N
        jumlahKeranjangBelanjaTF.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jumlahKeranjangBelanjaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jumlahKeranjangBelanjaTF))
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));

        subTotalTF.setFont(new java.awt.Font("Raleway", 1, 18)); // NOI18N
        subTotalTF.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subTotalTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(subTotalTF)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkoutBT)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(checkoutBT))
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(22, 22, 22)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void akunIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_akunIconMouseClicked
        // Get Mouse Position
//        int mPosX = MouseInfo.getPointerInfo().getLocation().x;
//        int mPosY = MouseInfo.getPointerInfo().getLocation().y;
        // Show Popup Menu
        popupMenu.show(this, 740, 110);
    }//GEN-LAST:event_akunIconMouseClicked

    private void spinnerProduk1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerProduk1StateChanged
        int value1 = (Integer) spinnerProduk1.getValue();
        int value2 = (Integer) spinnerProduk2.getValue();
        int value3 = (Integer) spinnerProduk3.getValue();
        int value4 = (Integer) spinnerProduk4.getValue();
        int value5 = (Integer) spinnerProduk5.getValue();
        int value6 = (Integer) spinnerProduk6.getValue();
        jumlahKeranjangBelanjaTF.setText(Integer.toString(value1 + value2 + value3 + value4 + value5 + value6));

        // totalBelanja
        int hargaProdukTotal = (Integer.parseInt(hargaProduk1.getText()) * value1)
                + (Integer.parseInt(hargaProduk2.getText()) * value2)
                + (Integer.parseInt(hargaProduk3.getText()) * value3)
                + (Integer.parseInt(hargaProduk4.getText()) * value4)
                + (Integer.parseInt(hargaProduk5.getText()) * value5)
                + (Integer.parseInt(hargaProduk6.getText()) * value6);
        subTotalTF.setText(String.valueOf(hargaProdukTotal));
    }//GEN-LAST:event_spinnerProduk1StateChanged

    private void spinnerProduk2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerProduk2StateChanged
        int value1 = (Integer) spinnerProduk1.getValue();
        int value2 = (Integer) spinnerProduk2.getValue();
        int value3 = (Integer) spinnerProduk3.getValue();
        int value4 = (Integer) spinnerProduk4.getValue();
        int value5 = (Integer) spinnerProduk5.getValue();
        int value6 = (Integer) spinnerProduk6.getValue();
        jumlahKeranjangBelanjaTF.setText(Integer.toString(value1 + value2 + value3 + value4 + value5 + value6));

        // totalBelanja
        int hargaProdukTotal = (Integer.parseInt(hargaProduk1.getText()) * value1)
                + (Integer.parseInt(hargaProduk2.getText()) * value2)
                + (Integer.parseInt(hargaProduk3.getText()) * value3)
                + (Integer.parseInt(hargaProduk4.getText()) * value4)
                + (Integer.parseInt(hargaProduk5.getText()) * value5)
                + (Integer.parseInt(hargaProduk6.getText()) * value6);
        subTotalTF.setText(String.valueOf(hargaProdukTotal));
    }//GEN-LAST:event_spinnerProduk2StateChanged

    private void spinnerProduk3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerProduk3StateChanged
        int value1 = (Integer) spinnerProduk1.getValue();
        int value2 = (Integer) spinnerProduk2.getValue();
        int value3 = (Integer) spinnerProduk3.getValue();
        int value4 = (Integer) spinnerProduk4.getValue();
        int value5 = (Integer) spinnerProduk5.getValue();
        int value6 = (Integer) spinnerProduk6.getValue();
        jumlahKeranjangBelanjaTF.setText(Integer.toString(value1 + value2 + value3 + value4 + value5 + value6));

        // totalBelanja
        int hargaProdukTotal = (Integer.parseInt(hargaProduk1.getText()) * value1)
                + (Integer.parseInt(hargaProduk2.getText()) * value2)
                + (Integer.parseInt(hargaProduk3.getText()) * value3)
                + (Integer.parseInt(hargaProduk4.getText()) * value4)
                + (Integer.parseInt(hargaProduk5.getText()) * value5)
                + (Integer.parseInt(hargaProduk6.getText()) * value6);
        subTotalTF.setText(String.valueOf(hargaProdukTotal));
    }//GEN-LAST:event_spinnerProduk3StateChanged

    private void spinnerProduk4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerProduk4StateChanged
        int value1 = (Integer) spinnerProduk1.getValue();
        int value2 = (Integer) spinnerProduk2.getValue();
        int value3 = (Integer) spinnerProduk3.getValue();
        int value4 = (Integer) spinnerProduk4.getValue();
        int value5 = (Integer) spinnerProduk5.getValue();
        int value6 = (Integer) spinnerProduk6.getValue();
        jumlahKeranjangBelanjaTF.setText(Integer.toString(value1 + value2 + value3 + value4 + value5 + value6));

        // totalBelanja
        int hargaProdukTotal = (Integer.parseInt(hargaProduk1.getText()) * value1)
                + (Integer.parseInt(hargaProduk2.getText()) * value2)
                + (Integer.parseInt(hargaProduk3.getText()) * value3)
                + (Integer.parseInt(hargaProduk4.getText()) * value4)
                + (Integer.parseInt(hargaProduk5.getText()) * value5)
                + (Integer.parseInt(hargaProduk6.getText()) * value6);
        subTotalTF.setText(String.valueOf(hargaProdukTotal));
    }//GEN-LAST:event_spinnerProduk4StateChanged

    private void spinnerProduk5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerProduk5StateChanged
        int value1 = (Integer) spinnerProduk1.getValue();
        int value2 = (Integer) spinnerProduk2.getValue();
        int value3 = (Integer) spinnerProduk3.getValue();
        int value4 = (Integer) spinnerProduk4.getValue();
        int value5 = (Integer) spinnerProduk5.getValue();
        int value6 = (Integer) spinnerProduk6.getValue();
        jumlahKeranjangBelanjaTF.setText(Integer.toString(value1 + value2 + value3 + value4 + value5 + value6));

        // totalBelanja
        int hargaProdukTotal = (Integer.parseInt(hargaProduk1.getText()) * value1)
                + (Integer.parseInt(hargaProduk2.getText()) * value2)
                + (Integer.parseInt(hargaProduk3.getText()) * value3)
                + (Integer.parseInt(hargaProduk4.getText()) * value4)
                + (Integer.parseInt(hargaProduk5.getText()) * value5)
                + (Integer.parseInt(hargaProduk6.getText()) * value6);
        subTotalTF.setText(String.valueOf(hargaProdukTotal));
    }//GEN-LAST:event_spinnerProduk5StateChanged

    private void spinnerProduk6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerProduk6StateChanged
        int value1 = (Integer) spinnerProduk1.getValue();
        int value2 = (Integer) spinnerProduk2.getValue();
        int value3 = (Integer) spinnerProduk3.getValue();
        int value4 = (Integer) spinnerProduk4.getValue();
        int value5 = (Integer) spinnerProduk5.getValue();
        int value6 = (Integer) spinnerProduk6.getValue();
        jumlahKeranjangBelanjaTF.setText(Integer.toString(value1 + value2 + value3 + value4 + value5 + value6));

        // totalBelanja
        int hargaProdukTotal = (Integer.parseInt(hargaProduk1.getText()) * value1)
                + (Integer.parseInt(hargaProduk2.getText()) * value2)
                + (Integer.parseInt(hargaProduk3.getText()) * value3)
                + (Integer.parseInt(hargaProduk4.getText()) * value4)
                + (Integer.parseInt(hargaProduk5.getText()) * value5)
                + (Integer.parseInt(hargaProduk6.getText()) * value6);
        subTotalTF.setText(String.valueOf(hargaProdukTotal));
    }//GEN-LAST:event_spinnerProduk6StateChanged

    private void beliBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliBT1ActionPerformed
        if (subTotalTF.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "Keranjang Anda masih kosong, tambahkan terlebih dahulu!");
        } else {
            checkout.subtotal.setText(subTotalTF.getText());
            int ongkir = 0;
            if (Integer.valueOf(subTotalTF.getText()) < 100000) {
                ongkir = 10000;
            } else if (Integer.valueOf(subTotalTF.getText()) < 500000) {
                ongkir = 20000;
            } else {
                ongkir = 35000;
            }
            checkout.ongkir.setText(String.valueOf(ongkir));
            checkout.total.setText(String.valueOf(Integer.valueOf(subTotalTF.getText()) + ongkir));
            ViewLogin.getViewLogin().name = name;
            checkout.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_beliBT1ActionPerformed

    private void beliBT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliBT2ActionPerformed
        if (subTotalTF.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "Keranjang Anda masih kosong, tambahkan terlebih dahulu!");
        } else {
            checkout.subtotal.setText(subTotalTF.getText());
            int ongkir = 0;
            if (Integer.valueOf(subTotalTF.getText()) < 100000) {
                ongkir = 10000;
            } else if (Integer.valueOf(subTotalTF.getText()) < 500000) {
                ongkir = 20000;
            } else {
                ongkir = 35000;
            }
            checkout.ongkir.setText(String.valueOf(ongkir));
            checkout.total.setText(String.valueOf(Integer.valueOf(subTotalTF.getText()) + ongkir));
            ViewLogin.getViewLogin().name = name;
            checkout.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_beliBT2ActionPerformed

    private void beliBT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliBT3ActionPerformed
        if (subTotalTF.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "Keranjang Anda masih kosong, tambahkan terlebih dahulu!");
        } else {
            checkout.subtotal.setText(subTotalTF.getText());
            int ongkir = 0;
            if (Integer.valueOf(subTotalTF.getText()) < 100000) {
                ongkir = 10000;
            } else if (Integer.valueOf(subTotalTF.getText()) < 500000) {
                ongkir = 20000;
            } else {
                ongkir = 35000;
            }
            checkout.ongkir.setText(String.valueOf(ongkir));
            checkout.total.setText(String.valueOf(Integer.valueOf(subTotalTF.getText()) + ongkir));
            ViewLogin.getViewLogin().name = name;
            checkout.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_beliBT3ActionPerformed

    private void beliBT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliBT4ActionPerformed
        if (subTotalTF.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "Keranjang Anda masih kosong, tambahkan terlebih dahulu!");
        } else {
            checkout.subtotal.setText(subTotalTF.getText());
            int ongkir = 0;
            if (Integer.valueOf(subTotalTF.getText()) < 100000) {
                ongkir = 10000;
            } else if (Integer.valueOf(subTotalTF.getText()) < 500000) {
                ongkir = 20000;
            } else {
                ongkir = 35000;
            }
            checkout.ongkir.setText(String.valueOf(ongkir));
            checkout.total.setText(String.valueOf(Integer.valueOf(subTotalTF.getText()) + ongkir));
            ViewLogin.getViewLogin().name = name;
            checkout.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_beliBT4ActionPerformed

    private void beliBT5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliBT5ActionPerformed
        if (subTotalTF.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "Keranjang Anda masih kosong, tambahkan terlebih dahulu!");
        } else {
            checkout.subtotal.setText(subTotalTF.getText());
            int ongkir = 0;
            if (Integer.valueOf(subTotalTF.getText()) < 100000) {
                ongkir = 10000;
            } else if (Integer.valueOf(subTotalTF.getText()) < 500000) {
                ongkir = 20000;
            } else {
                ongkir = 35000;
            }
            checkout.ongkir.setText(String.valueOf(ongkir));
            checkout.total.setText(String.valueOf(Integer.valueOf(subTotalTF.getText()) + ongkir));
            ViewLogin.getViewLogin().name = name;
            checkout.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_beliBT5ActionPerformed

    private void beliBT6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliBT6ActionPerformed
        if (subTotalTF.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "Keranjang Anda masih kosong, tambahkan terlebih dahulu!");
        } else {
            checkout.subtotal.setText(subTotalTF.getText());
            int ongkir = 0;
            if (Integer.valueOf(subTotalTF.getText()) < 100000) {
                ongkir = 10000;
            } else if (Integer.valueOf(subTotalTF.getText()) < 500000) {
                ongkir = 20000;
            } else {
                ongkir = 35000;
            }
            checkout.ongkir.setText(String.valueOf(ongkir));
            checkout.total.setText(String.valueOf(Integer.valueOf(subTotalTF.getText()) + ongkir));
            ViewLogin.getViewLogin().name = name;
            checkout.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_beliBT6ActionPerformed

    private void checkoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBTActionPerformed
        if (subTotalTF.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "Keranjang Anda masih kosong, tambahkan terlebih dahulu!");
        } else {
            checkout.subtotal.setText(subTotalTF.getText());
            int ongkir = 0;
            if (Integer.valueOf(subTotalTF.getText()) < 100000) {
                ongkir = 10000;
            } else if (Integer.valueOf(subTotalTF.getText()) < 500000) {
                ongkir = 20000;
            } else {
                ongkir = 35000;
            }
            checkout.ongkir.setText(String.valueOf(ongkir));
            checkout.total.setText(String.valueOf(Integer.valueOf(subTotalTF.getText()) + ongkir));
            ViewLogin.getViewLogin().name = name;
            checkout.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_checkoutBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ViewMenuUtama().setVisible(true);
                } catch (IOException | SQLException ex) {
                    Logger.getLogger(ViewMenuUtama.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Create Menu Method
    private void createPopupMenu(JFrame frame) {
        // Create File Menu
        menuItem = new JMenuItem(
                "Akun Saya",
                new ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\Get Your Dimsum\\src\\icon\\account.png")
        );
        // Apply Desc
        menuItem.getAccessibleContext().setAccessibleDescription("Akun Saya");
        menuItem.setFont(new Font("MV Boli", Font.PLAIN, 20));
        // Create an Action Listener
        menuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {

                try {
                    ViewLogin.getViewLogin().name = name;
                    new ViewMenuAkunSayaEdit().setVisible(true);
                    dispose();
                } catch (IOException | SQLException ex) {
                    Logger.getLogger(ViewMenuUtama.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
        // Add Menu Item Into Popup Menu
        popupMenu.add(menuItem);

        // Add another menu item to popup menu
        menuItem = new JMenuItem(
                "Pesanan Saya",
                new ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\Get Your Dimsum\\src\\icon\\book.png")
        );
        // Apply Desc
        menuItem.getAccessibleContext().setAccessibleDescription("Pesanan Saya");
        menuItem.setFont(new Font("MV Boli", Font.PLAIN, 20));
        // Create an Action Listener
        menuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {

                    try {
                        ViewMenuPesananSaya pesanan = new ViewMenuPesananSaya();
                        if (pesanan.produkTB.getRowCount() == 0) { // pengecek row table 0
                            new ViewMenuPesananSayaEmpty().setVisible(true);
                            dispose();
                        } else {
                            ViewLogin.getViewLogin().name = name;
                            new ViewMenuPesananSaya().setVisible(true);
                            dispose();
                        }}catch (IOException | SQLException ex) {
                        Logger.getLogger(ViewMenuUtama.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }

            );
        // Add Menu Item Into Popup Menu
            popupMenu.add (menuItem);
            // Add another menu item to popup menu
            menuItem  = new JMenuItem(
                    "Settings",
                    new ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\Get Your Dimsum\\src\\icon\\settings.png")
            );
            // Apply Desc

            menuItem.getAccessibleContext ()

            .setAccessibleDescription("Settings");
            menuItem.setFont (
                    

            new Font("MV Boli", Font.PLAIN, 20));
        // Create an Action Listener
            menuItem.addActionListener (
                     
                new ActionListener() {
            @Override
                public void actionPerformed
                (ActionEvent ae
                
                
                    ) {
                
                try {
                        ViewLogin.getViewLogin().name = name;
                        ViewLogin.getViewLogin().pass = pass;
                        new ViewSettings().setVisible(true);
                        dispose();
                    } catch (IOException | SQLException ex) {
                        Logger.getLogger(ViewMenuUtama.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }

            );
        // Add Menu Item Into Popup Menu
            popupMenu.add (menuItem);

            // Add another menu item to popup menu
            menuItem  = new JMenuItem(
                    "Log-out",
                    new ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\Get Your Dimsum\\src\\icon\\logout.png")
            );
            // Apply Desc

            menuItem.getAccessibleContext ()

            .setAccessibleDescription("Log-out");
            menuItem.setFont (
                    

            new Font("MV Boli", Font.PLAIN, 20));
        // Create an Action Listener
            menuItem.addActionListener (
                     
                new ActionListener() {
            @Override
                public void actionPerformed
                (ActionEvent ae
                
                
                    ) {
                String tanya = "Apakah yakin mau Log-out?";
                    boolean yakin = JOptionPane.showOptionDialog(null, tanya, "Konfirmasi", JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null) == JOptionPane.YES_OPTION;
                    if (yakin) {
                        JOptionPane.showMessageDialog(frame, "Anda Telah Logout");
                        new ViewLogin().setVisible(true);
                        dispose();
                    }
                }
            }

            );
        // Add Menu Item Into Popup Menu
            popupMenu.add (menuItem);
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel akunIcon;
    private javax.swing.JButton beliBT1;
    private javax.swing.JButton beliBT2;
    private javax.swing.JButton beliBT3;
    private javax.swing.JButton beliBT4;
    private javax.swing.JButton beliBT5;
    private javax.swing.JButton beliBT6;
    private javax.swing.JButton checkoutBT;
    public static javax.swing.JLabel gambar1;
    public static javax.swing.JLabel gambar2;
    public static javax.swing.JLabel gambar3;
    public static javax.swing.JLabel gambar4;
    public static javax.swing.JLabel gambar5;
    public static javax.swing.JLabel gambar6;
    public static javax.swing.JLabel hargaProduk1;
    public static javax.swing.JLabel hargaProduk2;
    public static javax.swing.JLabel hargaProduk3;
    public static javax.swing.JLabel hargaProduk4;
    public static javax.swing.JLabel hargaProduk5;
    public static javax.swing.JLabel hargaProduk6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public static javax.swing.JLabel jumlahKeranjangBelanjaTF;
    public static javax.swing.JLabel namaProduk1;
    public static javax.swing.JLabel namaProduk2;
    public static javax.swing.JLabel namaProduk3;
    public static javax.swing.JLabel namaProduk4;
    public static javax.swing.JLabel namaProduk5;
    public static javax.swing.JLabel namaProduk6;
    public static javax.swing.JSpinner spinnerProduk1;
    public static javax.swing.JSpinner spinnerProduk2;
    public static javax.swing.JSpinner spinnerProduk3;
    public static javax.swing.JSpinner spinnerProduk4;
    public static javax.swing.JSpinner spinnerProduk5;
    public static javax.swing.JSpinner spinnerProduk6;
    public static javax.swing.JLabel subTotalTF;
    public static javax.swing.JLabel usernameLB;
    // End of variables declaration//GEN-END:variables
}

